#!/bin/bash
## @RequireVagrantFile @RequireVagrantPath

debug_dump "Command Line Params Passed to macro: '$COMMANDLINEPARAMS'"
if [[ ${COMMANDLINEPARAMS} =~ -.*u(.*)$ ]]; then
    USER=${BASH_REMATCH[1]}
else
    USER=dev
fi;

debug_dump "Running as user $USER"

if [[ ${REMOTEROOT} == "" ]]; then
    REMOTEROOT="/vagrant"
fi;

debug_dump "Working path: ${WORKPATH}"

debug_dump "Getting current directory..."
CURDIR=$(pwd);
debug_dump "... $CURDIR"

debug_dump "Getting path relative to project root"
RELDIR=${CURDIR#${VAGRANTFILEPATH}}

if [[ ${WORKPATH} == "./" ]]; then
    enter "${WORKPATH}"
    WORKPATHABS=$(pwd);
    RELDIR=${CURDIR#${WORKPATHABS}}
    leave
elif [[ ! ${WORKPATH} == "" ]]; then
    RELDIR=${CURDIR#${WORKPATH}}
fi;

debug_dump "... $RELDIR"

if [[ ${VAGRANTFILEPATH} =~ ^/ ]]; then
    WORKPATH=""
fi;
enter "${WORKPATH}${VAGRANTFILEPATH}"

debug_dump "Attempting ssh login..."
expect -c "set timeout 2; spawn ssh -p 2222 -t ${USER}@localhost \"cd ${REMOTEROOT}/${RELDIR}; bash\"; expect \"assword:\" { send \"password1\r\" }; expect \"]\$ \" {send \"clear\r\"};  interact"

leave