#!/bin/bash
## @RequireVagrantFile @RequireVagrantPath

if [[ ${REMOTEROOT} == "" ]]; then
    REMOTEROOT="/vagrant"
fi;

debug_dump "Working path: ${WORKPATH}"

debug_dump "Getting current directory..."
CURDIR=$(pwd);
debug_dump "... $CURDIR"

debug_dump "Getting path relative to project root (specify in vagrantenv)"
RELDIR=${CURDIR#${VAGRANTFILEPATH}}
if [[ ! ${WORKPATH} == "" ]]; then
    RELDIR=${CURDIR#${WORKPATH}}
fi;
debug_dump "... $RELDIR"

if [[ ${VAGRANTFILEPATH} =~ ^/ ]]; then
    WORKPATH=""
fi;
pushd "${WORKPATH}${VAGRANTFILEPATH}" 2>&1 > /dev/null

debug_dump "Attempting ssh login..."
"$RUNPATH" ssh -c "cd ${REMOTEROOT}/$RELDIR; bash"

popd 2>&1 > /dev/null