#! /bin/bash

echo "Beginning update"

debug_dump "Creating temp directory"
UPDATE_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'drifter')
enter ${UPDATE_DIR}

debug_dump "Pulling from repo"
git clone https://github.com/awilliams219/drifter.git

debug_dump "Calling installer."
enter drifter

echo "Enter your local user account admin password:"
./install.sh

leave

echo "Update complete"


